### ISSUE TITLE
where are the gfp scripts?

### ISSUE THREAD

**Issue by gldurst** [EliLillyCo/LillyMol#10]
Hi,
I just downloaded and compiled LillyMol version 3.0 for Linux-gcc-6.2.0 without complaints and I see most all the  binaries, but where are the new gfp tools? I did a search and only found the source code (.cc files) and test scripts... no gfp binaries. Where are they?
Thanks,
Greg

**Comment by G-Huang** [comment]
Hi Greg,
  The gfp tools shall be generated under you LillyMol root folder bin/Linux-gcc_6.2.0/ after you build the code. Please let me know if you could not find binary there.

Kind Regards,
Gordon

**Comment by G-Huang** [comment]
Hi Greg,
  I tested it using our default Linux-gcc-7.2.1 compiler and confirm the gfp binaries are generated under bin/Linux-gcc-7.2.1.  I could not confirm Linux-gcc-6.2.0 compiler because it is not available on our machine any more. I won’t be surprised that the Linux-gcc-6.20 build is missing something  because we cannot test this before release. If you find the root cause of this, please let me know because other folks who is using gcc-6.2.0 may have some issue you have.


Kind Regards,
Gordon

**Comment by gldurst** [comment]
Hi Gordon,
None of the gfp binaries were generated on my home linux box which has gcc-6.4.0 installed. I was able to compile LillyMol on my work linux box with gcc-7.2.1 and everything was compiled (including the gfp files). Are there different compiler options between the gcc versions? I noticed significant differences in the makefile.public.Linux-gcc-6.2.0 and 
makefile.public.Linux-gcc-7.2.1 files. There must be logic to choose between the two? Why won’t the gfp binaries compile with gcc-6.4.0? I would really like to get things running at home. I don’t know if I can upgrade gcc higher without other problems.

Thanks,
Greg

**Comment by G-Huang** [comment]
Hi Greg,
  Thank you for update. I will discuss with our team to see if I can get hands on a box with gcc-6.2.0 so that I can test and fix the build issue under older version gcc. I am not sure what will be the final decision. I will keep you posted.

Kind Regards,
Gordon

**Comment by G-Huang** [comment]
Hi Greg,
  I discussed this with team. We will not be able to support the gcc-6.2.0 due to the limit of resource we have. I think some of the build script is out-of-date for the gcc-6.2.0 when we moved to the 7.2 compiler. If you happen to fix those script please let me know, we may merge those to help others.

Kind Regards,
Gordon
