### ISSUE TITLE
rxn_standardize with discard rxns multiple products - expected behavior?

### ISSUE THREAD

**Issue by vfscalfani** [EliLillyCo/LillyMol#27]
Hello, 

I have some reaction smiles where I would like to filter out reactions with more than one product. I see that in `rxn_standardize` there is an option `-X rmmp, discard reactions that have multiple products`, however this does not seem to work for me and I am unclear if I am using this option incorrectly. When I try this option, reactions with multiple products do not get discarded.

Other relevant details:

I am using an older version, LillyMol 6 from here: https://github.com/IanAWatson/LillyMol_6_cmake

I have provided an example below. What I would very much like to know is if the latest version 7.1 would have the same output?  If not, then perhaps this is just a bug in the older version and I need to use the newer version. I would test that, but I don't fully understand the new build process yet. 

Thanks very much for your time,

Vin 

Example `myrxn` file, which I believe to have 2 products:

```
[CH2:1]1[C:10]2[C:5](=[CH:6][CH:7]=[CH:8][CH:9]=2)[CH2:4][CH2:3][C:2]1=O.[NH:12]1[CH2:17][CH:16]([C:18]([NH2:20])=[O:19])[O:15][CH2:14][CH2:13]1.C1(C)C=CC(S(O)(=O)=O)=CC=1>CC(C)=O>[C:1]1(=[O:15])[C:10]2[C:5](=[CH:6][CH:7]=[CH:8][CH:9]=2)[CH2:4][CH2:3][CH2:2]1.[NH:12]1[CH2:17][CH:16]([C:18]([NH2:20])=[O:19])[O:15][CH2:14][CH2:13]1
```

Command used:

```
rxn_standardize -s -v -K -X rmmp myrxn > out 2> log

```
Here is the log file:

```
Will fix Kekule problems
Input is a reaction smiles
Will discard reactions containing multiple products
Read 1 reactions
0 bad reactions ignored
input reactions had btw 31 and 31 ave 31 atoms
0 reactions with multiple products skipped
0 reactions with fragments not participating
0 reactions with reagents not participating
0 reactions with duplicate reagents
0 reactions with no mapped atoms in common btw LHS and RHS
0 reactions where the reagent count was changed
0 reactions with Kekule problems fixed
0 reactions discarded for more than 0 atoms in a reagent and a product
0 reactions discarded for aromatic bonds
1 reactions written (0 discarded)

```

out:

```
[CH2:1]1[C:10]2=[CH:9][CH:8]=[CH:7][CH:6]=[C:5]2[CH2:4][CH2:3][C:2]1=O.[NH:12]1[CH2:17][CH:16]([C:18]([NH2:20])=[O:19])[O:15][CH2:14][CH2:13]1.C1(C)=CC=C(C=C1)S(O)(=O)=O>CC(C)=O>[C:1]1(=[O:15])[C:10]2=[CH:9][CH:8]=[CH:7][CH:6]=[C:5]2[CH2:4][CH2:3][CH2:2]1.[NH:12]1[CH2:17][CH:16]([C:18]([NH2:20])=[O:19])[O:15][CH2:14][CH2:13]1
```

**Comment by xuyan-ru** [comment]
@vfscalfani Thanks for the bug report. You are correct, this is a bug.

The reason for the bug is that if the reaction is read from an ISIS Reaction file, then multiple products are part of that file structure. When reading reaction smiles however, the product(s) show up as a possibly dot disconnected molecule. But that was being interpreted as one product molecule – that happened to have multiple fragments.
 
We have just changed the code to the following logic:
 
If the number of products as read is > 1
OR
If there is just 1 product molecule and it contains multiple fragments
 
The only possible modification of this is that we can see situations where some multiple fragment products might be OK – say a single atom, while other multiple fragment products may not be OK. If that ever arises, we could add an option to specify a threshold on meaningful atom count in the products.
 
Sorry for the bug, but thank you for bringing it to our attention. It will be fixed in an upcoming release of LillyMol, and in the meantime, Ian Watson has made this fix at https://github.com/IanAWatson/LillyMol_6_cmake.
 
Please give that a try and let us know if you find further problems.
 
We hope that LillyMol is proving useful to you.
 
Thanks

**Comment by vfscalfani** [comment]
Hi @xuyan-ru. Thank you so much for the detailed explanation and bug fix!

I tested with a few more examples; it works great and I am getting the expected results. 

Thanks again, 

Vin

**Comment by xuyan-ru** [comment]
Thanks Vin for confirming this, I will mark this issue as closed.
