### ISSUE TITLE
medchem rules queries

### ISSUE THREAD

**Issue by jmoch** [EliLillyCo/LillyMol#31]
Hello!

I noticed that the MCR queries are now added to the data folder.  Can these now be used with iwdemerit?  Or is there another way to use them?  I tried using them in my lillymol 6.0 version but I noticed that they appear to be a different format than the MCR queries and do not work in the following command I was trying to use:

`iwdemerit -A D -A I -S foo -G - -f 99999 -t -W imp2exp -W maxe=1 -E autocreate -qF:/home/jochoada/LillyMol-master/data/queries/medchemrules/mcr_queries -O hard -W dnv=0 -W slist -i smi smiles_fixed_std.smi > smi_demerit.smi`

Thanks in advance!

Jason

**Comment by xuyan-ru** [comment]
Hi Jason, please find below the response from Ian:

The current release of LillyMol is designed to be as upwardly compatible as possible with previous releases, and indeed the current executables can be used with the Lilly Medchem Rules.
 
But in the very specific example you have above, use the input file ‘demerits’ instead of ‘mcr_queries’ and it will work. For iwdemerit, which applies the demerit values, all queries must have a numeric value for the demerit value. That is why what you had above did not work.
 
But if you would like to use the new executables with the Medchem rules it is easy.
 
git clone https://github.com/IanAWatson/Lilly-Medchem-Rules
cd Lilly-Medchem-Rules
 
skip the ‘make’ step, we will use executables from LillyMol 7.x already built elsewhere.
Use the undocumented -bindir option to specify a directory in which executables can be found
 
./Lilly_Medchem_Rules.rb -bindir /home/you/path/to/LillyMol/bin/Linux -v … file.smi > okmedchem.smi
 
Will use the new executables. Make sure you use the -v option so it shows you what it is doing.
 
I did a quick comparison across 10k random Chembl molecules and concordance is good.
 
Old version passes 6081, new version passes 6088
 
ClC1=CC(=CC=C1)NC1=C(OCC)C(=O)C1=O CHEMBL1726037
 
Is now hit by keto_carbonyl but was previously matched by vinyl_ether_thioate_isoamide. But perhaps it should be matched by neither if that ring were considered aromatic? What do you think?
 
C1(=C(C)C(=O)C2=C(N3C=CC(=CC3=C2C(C)=O)OC)C1=O)C CHEMBL1935248 now matches vinyl_ether_thioate_isoamide due to a change in aromaticity perception. I think I liked the old way better, we may restructure that query.
 
And C1=CC=C2C3=C1C1=NC(=O)C(=C1C3=CC=C2N1CCSCC1)NC(C)C CHEMBL2312478 now matches too_many_aromatic_rings_in_ring_system which again is due to a change in aromaticity perception, but which this time looks better in the new version.
 
And I made a minor correction to how atom count demerits are computed, so many molecules in the bad3 file have small differences in demerit values.
 
So almost all of the differences are due to changes in the underlying aromaticity perception algorithm, which is a net improvement over the previous version, although as we see above, not always. Aromaticity is such a difficult subject, I am thinking we might be better off running with the ‘-A ALLPI’ option, which specifies that if all atoms in a ring have a pi electron(s) then the ring is aromatic. Forget Kekule…
 
Run-time might be slightly in favor of the old version – both take around 1.8 seconds to process the 10k molecules.
 
Please let us know if you have any questions or problems.

**Comment by jmoch** [comment]
Hi Xuyan and Ian!

Thanks so much for the quick response!  I did try the demerits file but thought it was hanging.  In fact it was just processing and it does go to completion giving the expected output.  This is fantastic.  I did see some output mentioned that I'm not sure the cause.  I did try adjusting -W maxe=1 to other values like 999 but did not see a difference.  Other than that message everything looks great!  Thanks again so much!

Thanks!
Jason

Single_Substructure_Query::_construct_from_msi_object: Root atom not found
Parsed '' now Expression with 1 operators .|.
Single_Substructure_Query::_construct_from_msi_object: Root atom not found
Single_Substructure_Query::_construct_from_msi_object: Root atom not found
Single_Substructure_Query::set_max_matches_to_find:not set due to _hits_needed
Single_Substructure_Query::set_max_matches_to_find:not set due to _hits_needed
Single_Substructure_Query::set_max_matches_to_find:not set due to _hits_needed
Single_Substructure_Query::set_max_matches_to_find:not set due to _hits_needed
Single_Substructure_Query::set_max_matches_to_find:not set due to _hits_needed

**Comment by xuyan-ru** [comment]
Hi Jason I'm closing this issue as I assume these verbose messages should be depressed when verbose is not turned on... please let us know if you still have problems!
